# best
python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr1.0.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 200 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm1 --result_path sc_java_w200d_tp1_ml256_q_astm1_lstm128
python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr0.75.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 50  --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm2 --result_path sc_java_w50d_tp075_ml256_q_astm2_lstm128
python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr0.75.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 200 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm1 --result_path sc_android_w200d_tp075_ml256_q_astm1_lstm64
python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr0.75.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 100 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm2 --result_path sc_android_w100d_tp075_ml256_q_astm2_lstm64
python train.py --dataset c# --data_path ./data/so_c#.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_c#_questions_tr0.75.pkl --skill_cluster_path ./data/C#Cluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 150 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm1 --result_path sc_c#_w150d_tp075_ml256_q_astm1_lstm64
python train.py --dataset c# --data_path ./data/so_c#.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_c#_questions_tr0.75.pkl --skill_cluster_path ./data/C#Cluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 50  --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm2 --result_path sc_c#_w50d_tp075_ml256_q_astm2_lstm64

# others
python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr1.0.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 50  --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm1 --result_path sc_java_w50d_tp1_ml256_q_astm1_lstm128
python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr1.0.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 50  --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm2 --result_path sc_java_w50d_tp1_ml256_q_astm2_lstm128
python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr1.0.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 100 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm1 --result_path sc_java_w100d_tp1_ml256_q_astm1_lstm128
python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr1.0.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 100 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm2 --result_path sc_java_w100d_tp1_ml256_q_astm2_lstm128
python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr1.0.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 150 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm1 --result_path sc_java_w150d_tp1_ml256_q_astm1_lstm128
python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr1.0.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 150 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm2 --result_path sc_java_w150d_tp1_ml256_q_astm2_lstm128

python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr1.0.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 50  --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm1 --result_path sc_android_w50d_tp1_ml256_q_astm1_lstm128
python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr1.0.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 50  --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm2 --result_path sc_android_w50d_tp1_ml256_q_astm2_lstm128
python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr1.0.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 100 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm1 --result_path sc_android_w100d_tp1_ml256_q_astm1_lstm128
python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr1.0.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 100 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm2 --result_path sc_android_w100d_tp1_ml256_q_astm2_lstm128
python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr1.0.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 150 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm1 --result_path sc_android_w150d_tp1_ml256_q_astm1_lstm128
python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr1.0.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 150 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm2 --result_path sc_android_w150d_tp1_ml256_q_astm2_lstm128
python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr1.0.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 200 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm1 --result_path sc_android_w200d_tp1_ml256_q_astm1_lstm128
python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr1.0.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 200 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm2 --result_path sc_android_w200d_tp1_ml256_q_astm2_lstm128

python train.py --dataset c# --data_path ./data/so_c#.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_c#_questions_tr1.0.pkl --skill_cluster_path ./data/C#Cluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 50  --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm1 --result_path sc_c#_w50d_tp1_ml256_q_astm1_lstm128
python train.py --dataset c# --data_path ./data/so_c#.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_c#_questions_tr1.0.pkl --skill_cluster_path ./data/C#Cluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 100 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm1 --result_path sc_c#_w100d_tp1_ml256_q_astm1_lstm128
python train.py --dataset c# --data_path ./data/so_c#.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_c#_questions_tr1.0.pkl --skill_cluster_path ./data/C#Cluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 150 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm1 --result_path sc_c#_w150d_tp1_ml256_q_astm1_lstm128
python train.py --dataset c# --data_path ./data/so_c#.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_c#_questions_tr1.0.pkl --skill_cluster_path ./data/C#Cluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 200 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm1 --result_path sc_c#_w200d_tp1_ml256_q_astm1_lstm128

python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr1.0.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 50  --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm1 --result_path sc_java_w50d_tp1_ml256_q_astm1_lstm64
python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr1.0.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 50  --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm2 --result_path sc_java_w50d_tp1_ml256_q_astm2_lstm64
python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr1.0.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 100 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm1 --result_path sc_java_w100d_tp1_ml256_q_astm1_lstm64
python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr1.0.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 100 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm2 --result_path sc_java_w100d_tp1_ml256_q_astm2_lstm64
python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr1.0.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 150 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm1 --result_path sc_java_w150d_tp1_ml256_q_astm1_lstm64
python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr1.0.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 150 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm2 --result_path sc_java_w150d_tp1_ml256_q_astm2_lstm64
python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr1.0.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 200 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm1 --result_path sc_java_w200d_tp1_ml256_q_astm1_lstm64
python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr1.0.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 200 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm2 --result_path sc_java_w200d_tp1_ml256_q_astm2_lstm64

python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr1.0.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 50  --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm1 --result_path sc_android_w50d_tp1_ml256_q_astm1_lstm64
python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr1.0.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 50  --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm2 --result_path sc_android_w50d_tp1_ml256_q_astm2_lstm64
python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr1.0.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 100 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm1 --result_path sc_android_w100d_tp1_ml256_q_astm1_lstm64
python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr1.0.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 100 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm2 --result_path sc_android_w100d_tp1_ml256_q_astm2_lstm64
python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr1.0.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 150 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm1 --result_path sc_android_w150d_tp1_ml256_q_astm1_lstm64
python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr1.0.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 150 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm2 --result_path sc_android_w150d_tp1_ml256_q_astm2_lstm64
python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr1.0.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 200 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm1 --result_path sc_android_w200d_tp1_ml256_q_astm1_lstm64
python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr1.0.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 200 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm2 --result_path sc_android_w200d_tp1_ml256_q_astm2_lstm64

python train.py --dataset c# --data_path ./data/so_c#.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_c#_questions_tr1.0.pkl --skill_cluster_path ./data/C#Cluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 50  --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm1 --result_path sc_c#_w50d_tp1_ml256_q_astm1_lstm64
python train.py --dataset c# --data_path ./data/so_c#.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_c#_questions_tr1.0.pkl --skill_cluster_path ./data/C#Cluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 50  --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm2 --result_path sc_c#_w50d_tp1_ml256_q_astm2_lstm64
python train.py --dataset c# --data_path ./data/so_c#.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_c#_questions_tr1.0.pkl --skill_cluster_path ./data/C#Cluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 100 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm1 --result_path sc_c#_w100d_tp1_ml256_q_astm1_lstm64
python train.py --dataset c# --data_path ./data/so_c#.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_c#_questions_tr1.0.pkl --skill_cluster_path ./data/C#Cluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 100 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm2 --result_path sc_c#_w100d_tp1_ml256_q_astm2_lstm64
python train.py --dataset c# --data_path ./data/so_c#.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_c#_questions_tr1.0.pkl --skill_cluster_path ./data/C#Cluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 150 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm1 --result_path sc_c#_w150d_tp1_ml256_q_astm1_lstm64
python train.py --dataset c# --data_path ./data/so_c#.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_c#_questions_tr1.0.pkl --skill_cluster_path ./data/C#Cluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 150 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm2 --result_path sc_c#_w150d_tp1_ml256_q_astm2_lstm64
python train.py --dataset c# --data_path ./data/so_c#.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_c#_questions_tr1.0.pkl --skill_cluster_path ./data/C#Cluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 200 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm1 --result_path sc_c#_w200d_tp1_ml256_q_astm1_lstm64
python train.py --dataset c# --data_path ./data/so_c#.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_c#_questions_tr1.0.pkl --skill_cluster_path ./data/C#Cluster.csv --train_part 1.0 --post_type question --num_words 5000 --word_vector_dim 200 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm2 --result_path sc_c#_w200d_tp1_ml256_q_astm2_lstm64

python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr0.75.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 50  --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm1 --result_path sc_java_w50d_tp075_ml256_q_astm1_lstm128
python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr0.75.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 100 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm1 --result_path sc_java_w100d_tp075_ml256_q_astm1_lstm128
python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr0.75.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 100 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm2 --result_path sc_java_w100d_tp075_ml256_q_astm2_lstm128
python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr0.75.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 150 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm1 --result_path sc_java_w150d_tp075_ml256_q_astm1_lstm128
python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr0.75.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 150 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm2 --result_path sc_java_w150d_tp075_ml256_q_astm2_lstm128
python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr0.75.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 200 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm1 --result_path sc_java_w200d_tp075_ml256_q_astm1_lstm128
python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr0.75.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 200 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm2 --result_path sc_java_w200d_tp075_ml256_q_astm2_lstm128

python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr0.75.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 50  --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm1 --result_path sc_android_w50d_tp075_ml256_q_astm1_lstm128
python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr0.75.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 50  --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm2 --result_path sc_android_w50d_tp075_ml256_q_astm2_lstm128
python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr0.75.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 100 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm1 --result_path sc_android_w100d_tp075_ml256_q_astm1_lstm128
python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr0.75.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 100 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm2 --result_path sc_android_w100d_tp075_ml256_q_astm2_lstm128
python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr0.75.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 150 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm1 --result_path sc_android_w150d_tp075_ml256_q_astm1_lstm128
python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr0.75.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 150 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm2 --result_path sc_android_w150d_tp075_ml256_q_astm2_lstm128
python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr0.75.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 200 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm1 --result_path sc_android_w200d_tp075_ml256_q_astm1_lstm128
python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr0.75.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 200 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm2 --result_path sc_android_w200d_tp075_ml256_q_astm2_lstm128

python train.py --dataset c# --data_path ./data/so_c#.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_c#_questions_tr0.75.pkl --skill_cluster_path ./data/C#Cluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 50  --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm1 --result_path sc_c#_w50d_tp075_ml256_q_astm1_lstm128
python train.py --dataset c# --data_path ./data/so_c#.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_c#_questions_tr0.75.pkl --skill_cluster_path ./data/C#Cluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 50  --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm2 --result_path sc_c#_w50d_tp075_ml256_q_astm2_lstm128
python train.py --dataset c# --data_path ./data/so_c#.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_c#_questions_tr0.75.pkl --skill_cluster_path ./data/C#Cluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 100 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm1 --result_path sc_c#_w100d_tp075_ml256_q_astm1_lstm128
python train.py --dataset c# --data_path ./data/so_c#.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_c#_questions_tr0.75.pkl --skill_cluster_path ./data/C#Cluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 100 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm2 --result_path sc_c#_w100d_tp075_ml256_q_astm2_lstm128
python train.py --dataset c# --data_path ./data/so_c#.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_c#_questions_tr0.75.pkl --skill_cluster_path ./data/C#Cluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 150 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm1 --result_path sc_c#_w150d_tp075_ml256_q_astm1_lstm128
python train.py --dataset c# --data_path ./data/so_c#.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_c#_questions_tr0.75.pkl --skill_cluster_path ./data/C#Cluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 150 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm2 --result_path sc_c#_w150d_tp075_ml256_q_astm2_lstm128
python train.py --dataset c# --data_path ./data/so_c#.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_c#_questions_tr0.75.pkl --skill_cluster_path ./data/C#Cluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 200 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm1 --result_path sc_c#_w200d_tp075_ml256_q_astm1_lstm128
python train.py --dataset c# --data_path ./data/so_c#.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_c#_questions_tr0.75.pkl --skill_cluster_path ./data/C#Cluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 200 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 128 --model_name astm2 --result_path sc_c#_w200d_tp075_ml256_q_astm2_lstm128

python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr0.75.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 50  --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm1 --result_path sc_java_w50d_tp075_ml256_q_astm1_lstm64
python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr0.75.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 50  --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm2 --result_path sc_java_w50d_tp075_ml256_q_astm2_lstm64
python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr0.75.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 100 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm1 --result_path sc_java_w100d_tp075_ml256_q_astm1_lstm64
python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr0.75.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 100 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm2 --result_path sc_java_w100d_tp075_ml256_q_astm2_lstm64
python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr0.75.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 150 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm1 --result_path sc_java_w150d_tp075_ml256_q_astm1_lstm64
python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr0.75.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 150 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm2 --result_path sc_java_w150d_tp075_ml256_q_astm2_lstm64
python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr0.75.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 200 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm1 --result_path sc_java_w200d_tp075_ml256_q_astm1_lstm64
python train.py --dataset java --data_path ./data/so_java.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_java_questions_tr0.75.pkl --skill_cluster_path ./data/JavaCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 200 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm2 --result_path sc_java_w200d_tp075_ml256_q_astm2_lstm64

python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr0.75.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 50  --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm1 --result_path sc_android_w50d_tp075_ml256_q_astm1_lstm64
python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr0.75.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 50  --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm2 --result_path sc_android_w50d_tp075_ml256_q_astm2_lstm64
python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr0.75.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 100 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm1 --result_path sc_android_w100d_tp075_ml256_q_astm1_lstm64
python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr0.75.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 150 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm1 --result_path sc_android_w150d_tp075_ml256_q_astm1_lstm64
python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr0.75.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 150 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm2 --result_path sc_android_w150d_tp075_ml256_q_astm2_lstm64
python train.py --dataset android --data_path ./data/so_android.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_android_questions_tr0.75.pkl --skill_cluster_path ./data/AndroidCluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 200 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm2 --result_path sc_android_w200d_tp075_ml256_q_astm2_lstm64

python train.py --dataset c# --data_path ./data/so_c#.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_c#_questions_tr0.75.pkl --skill_cluster_path ./data/C#Cluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 50  --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm1 --result_path sc_c#_w50d_tp075_ml256_q_astm1_lstm64
python train.py --dataset c# --data_path ./data/so_c#.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_c#_questions_tr0.75.pkl --skill_cluster_path ./data/C#Cluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 100 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm1 --result_path sc_c#_w100d_tp075_ml256_q_astm1_lstm64
python train.py --dataset c# --data_path ./data/so_c#.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_c#_questions_tr0.75.pkl --skill_cluster_path ./data/C#Cluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 100 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm2 --result_path sc_c#_w100d_tp075_ml256_q_astm2_lstm64
python train.py --dataset c# --data_path ./data/so_c#.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_c#_questions_tr0.75.pkl --skill_cluster_path ./data/C#Cluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 150 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm2 --result_path sc_c#_w150d_tp075_ml256_q_astm2_lstm64
python train.py --dataset c# --data_path ./data/so_c#.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_c#_questions_tr0.75.pkl --skill_cluster_path ./data/C#Cluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 200 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm1 --result_path sc_c#_w200d_tp075_ml256_q_astm1_lstm64
python train.py --dataset c# --data_path ./data/so_c#.txt --word_topic_vectors_path ./data/ --word_index_dir ./data/ --samples_path ./data/sa_sample_c#_questions_tr0.75.pkl --skill_cluster_path ./data/C#Cluster.csv --train_part 0.75 --post_type question --num_words 5000 --word_vector_dim 200 --max_sentence_len 256 --epochs 10 --batch_size 32 --lstm_dim 64 --model_name astm2 --result_path sc_c#_w200d_tp075_ml256_q_astm2_lstm64
